server:  port: 8090

spring:
  application:
    name: service-one
    
  datasource:    url: jdbc:h2:mem:testdb
  
  h2:    console:      enabled: true
      path: /h2-console
      
logging:  file:    name: /var/tmp/logs/${spring.application.name}/${spring.application.name}.log
  level:    root: info
    poc.kafka: debug
 
 
kafka:
  kafkaConsumer:
    bootstrap.servers: 'localhost:9092' #Brokers
    group.id: 'service-one-consumers'
    enable.auto.commit: true
    #auto.commit.interval.ms: 5000
    fetch.min.bytes: 100000
    session.timeout.ms: 60000
    auto.offset.reset: 'earliest'
    max.poll.records: 5000
    key.deserializer: 'org.apache.kafka.common.serialization.LongDeserializer'
    #value.deserializer: 'org.apache.kafka.common.serialization.ByteBufferDeserializer'
    value.deserializer: 'poc.kafka.serialization.MessageStatusDeserializer'

  kafkaProducer:
    #Kafka configuration changes according to the use cases
    bootstrap.servers: 'localhost:9092' #Brokers
    acks: 'all'
    batch.size: 150000
    buffer.memory: 33554432
    #client.id: 8
    retries: 1
    linger.ms: 10
    compression.type: 'lz4'
    key.serializer: 'org.apache.kafka.common.serialization.LongSerializer'
    value.serializer: 'poc.kafka.serialization.MessageSerializer'
    
  metaData:
    toTopic: message-to-send3    fromTopic: message-status3
